// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bcc_barycentric_cpp
List bcc_barycentric_cpp(const NumericMatrix& coords, const double s, const NumericVector& origin, const double tol, const int n_threads);
RcppExport SEXP _FastPotts_bcc_barycentric_cpp(SEXP coordsSEXP, SEXP sSEXP, SEXP originSEXP, SEXP tolSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type origin(originSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bcc_barycentric_cpp(coords, s, origin, tol, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// build_lattice_neighbor_edges_cpp
DataFrame build_lattice_neighbor_edges_cpp(const IntegerMatrix& basis_lattice, const int basis_id, const double s);
RcppExport SEXP _FastPotts_build_lattice_neighbor_edges_cpp(SEXP basis_latticeSEXP, SEXP basis_idSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type basis_lattice(basis_latticeSEXP);
    Rcpp::traits::input_parameter< const int >::type basis_id(basis_idSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(build_lattice_neighbor_edges_cpp(basis_lattice, basis_id, s));
    return rcpp_result_gen;
END_RCPP
}
// build_potts_lbp_graph
List build_potts_lbp_graph(SEXP mat, const bool drop_diagonal, const bool check_reverse);
RcppExport SEXP _FastPotts_build_potts_lbp_graph(SEXP matSEXP, SEXP drop_diagonalSEXP, SEXP check_reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const bool >::type drop_diagonal(drop_diagonalSEXP);
    Rcpp::traits::input_parameter< const bool >::type check_reverse(check_reverseSEXP);
    rcpp_result_gen = Rcpp::wrap(build_potts_lbp_graph(mat, drop_diagonal, check_reverse));
    return rcpp_result_gen;
END_RCPP
}
// build_potts_lbp_graph_from_edges
List build_potts_lbp_graph_from_edges(const IntegerVector& from, const IntegerVector& to, const NumericVector& weights, const int n_nodes, const bool symmetric, const bool check_reverse);
RcppExport SEXP _FastPotts_build_potts_lbp_graph_from_edges(SEXP fromSEXP, SEXP toSEXP, SEXP weightsSEXP, SEXP n_nodesSEXP, SEXP symmetricSEXP, SEXP check_reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type from(fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type to(toSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< const bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< const bool >::type check_reverse(check_reverseSEXP);
    rcpp_result_gen = Rcpp::wrap(build_potts_lbp_graph_from_edges(from, to, weights, n_nodes, symmetric, check_reverse));
    return rcpp_result_gen;
END_RCPP
}
// hilbert_index_scaled_cpp
SEXP hilbert_index_scaled_cpp(NumericMatrix coords, int bits, bool return_scaled);
RcppExport SEXP _FastPotts_hilbert_index_scaled_cpp(SEXP coordsSEXP, SEXP bitsSEXP, SEXP return_scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< int >::type bits(bitsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_scaled(return_scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(hilbert_index_scaled_cpp(coords, bits, return_scaled));
    return rcpp_result_gen;
END_RCPP
}
// openmp_enabled_cpp
bool openmp_enabled_cpp();
RcppExport SEXP _FastPotts_openmp_enabled_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(openmp_enabled_cpp());
    return rcpp_result_gen;
END_RCPP
}
// omp_max_threads_cpp
int omp_max_threads_cpp();
RcppExport SEXP _FastPotts_omp_max_threads_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(omp_max_threads_cpp());
    return rcpp_result_gen;
END_RCPP
}
// potts_lbp_cpp
List potts_lbp_cpp(const IntegerVector& adj_ptr, const IntegerVector& adj_idx, const IntegerVector& rev_idx, const NumericVector& edge_weights, const NumericMatrix& node_potential, const int max_iter, const float damping, const float tol, const bool synchronous);
RcppExport SEXP _FastPotts_potts_lbp_cpp(SEXP adj_ptrSEXP, SEXP adj_idxSEXP, SEXP rev_idxSEXP, SEXP edge_weightsSEXP, SEXP node_potentialSEXP, SEXP max_iterSEXP, SEXP dampingSEXP, SEXP tolSEXP, SEXP synchronousSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type adj_ptr(adj_ptrSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type adj_idx(adj_idxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type rev_idx(rev_idxSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type edge_weights(edge_weightsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type node_potential(node_potentialSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const float >::type damping(dampingSEXP);
    Rcpp::traits::input_parameter< const float >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const bool >::type synchronous(synchronousSEXP);
    rcpp_result_gen = Rcpp::wrap(potts_lbp_cpp(adj_ptr, adj_idx, rev_idx, edge_weights, node_potential, max_iter, damping, tol, synchronous));
    return rcpp_result_gen;
END_RCPP
}
// potts_lbp_parallel_cpp
List potts_lbp_parallel_cpp(const IntegerVector& adj_ptr, const IntegerVector& adj_idx, const IntegerVector& rev_idx, const NumericVector& edge_weights, const NumericMatrix& node_potential, const int max_iter, const float damping, const float tol, Nullable<int> n_threads, const bool verbose);
RcppExport SEXP _FastPotts_potts_lbp_parallel_cpp(SEXP adj_ptrSEXP, SEXP adj_idxSEXP, SEXP rev_idxSEXP, SEXP edge_weightsSEXP, SEXP node_potentialSEXP, SEXP max_iterSEXP, SEXP dampingSEXP, SEXP tolSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type adj_ptr(adj_ptrSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type adj_idx(adj_idxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type rev_idx(rev_idxSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type edge_weights(edge_weightsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type node_potential(node_potentialSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const float >::type damping(dampingSEXP);
    Rcpp::traits::input_parameter< const float >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(potts_lbp_parallel_cpp(adj_ptr, adj_idx, rev_idx, edge_weights, node_potential, max_iter, damping, tol, n_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// spatial_basis_objective_cpp
List spatial_basis_objective_cpp(const NumericVector& par, const IntegerMatrix& basis_id, const NumericMatrix& basis_weight, const IntegerVector& gene_index, const NumericMatrix& log_signature, const IntegerVector& edge_from, const IntegerVector& edge_to, const NumericVector& edge_distance, const double lambda, const int regularization, const double delta, const double sigma, const int purity, const double purity_lambda, const int n_threads, const int n_basis, const int n_cell_types);
RcppExport SEXP _FastPotts_spatial_basis_objective_cpp(SEXP parSEXP, SEXP basis_idSEXP, SEXP basis_weightSEXP, SEXP gene_indexSEXP, SEXP log_signatureSEXP, SEXP edge_fromSEXP, SEXP edge_toSEXP, SEXP edge_distanceSEXP, SEXP lambdaSEXP, SEXP regularizationSEXP, SEXP deltaSEXP, SEXP sigmaSEXP, SEXP puritySEXP, SEXP purity_lambdaSEXP, SEXP n_threadsSEXP, SEXP n_basisSEXP, SEXP n_cell_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type basis_id(basis_idSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type basis_weight(basis_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type gene_index(gene_indexSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type log_signature(log_signatureSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type edge_from(edge_fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type edge_to(edge_toSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type edge_distance(edge_distanceSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type regularization(regularizationSEXP);
    Rcpp::traits::input_parameter< const double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const int >::type purity(puritySEXP);
    Rcpp::traits::input_parameter< const double >::type purity_lambda(purity_lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_basis(n_basisSEXP);
    Rcpp::traits::input_parameter< const int >::type n_cell_types(n_cell_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_basis_objective_cpp(par, basis_id, basis_weight, gene_index, log_signature, edge_from, edge_to, edge_distance, lambda, regularization, delta, sigma, purity, purity_lambda, n_threads, n_basis, n_cell_types));
    return rcpp_result_gen;
END_RCPP
}
// spatial_basis_predict_cpp
List spatial_basis_predict_cpp(const NumericVector& par, const IntegerMatrix& basis_id, const NumericMatrix& basis_weight, const IntegerVector& gene_index, const NumericMatrix& log_signature, const int n_basis, const int n_threads, const int n_cell_types);
RcppExport SEXP _FastPotts_spatial_basis_predict_cpp(SEXP parSEXP, SEXP basis_idSEXP, SEXP basis_weightSEXP, SEXP gene_indexSEXP, SEXP log_signatureSEXP, SEXP n_basisSEXP, SEXP n_threadsSEXP, SEXP n_cell_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type basis_id(basis_idSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type basis_weight(basis_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type gene_index(gene_indexSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type log_signature(log_signatureSEXP);
    Rcpp::traits::input_parameter< const int >::type n_basis(n_basisSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_cell_types(n_cell_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_basis_predict_cpp(par, basis_id, basis_weight, gene_index, log_signature, n_basis, n_threads, n_cell_types));
    return rcpp_result_gen;
END_RCPP
}
// spatial_density_objective_cpp
List spatial_density_objective_cpp(const NumericVector& par, const IntegerMatrix& obs_basis_id, const NumericMatrix& obs_basis_weight, const IntegerMatrix& obs_edge_id, const NumericMatrix& obs_weight, const IntegerMatrix& quad_basis_id, const NumericMatrix& quad_basis_weight, const IntegerMatrix& quad_edge_id, const NumericVector& quad_weight, const IntegerVector& pair_from, const IntegerVector& pair_to, const IntegerVector& smooth_edge_from, const IntegerVector& smooth_edge_to, const NumericVector& smooth_edge_distance, const NumericVector& density_floor, const double lambda_eta, const double lambda_s_smooth, const double lambda_s_prior, const double s_prior_mean, const double lambda_edge, const int n_basis, const int n_edge_coef, const int n_cell_types, const int n_threads);
RcppExport SEXP _FastPotts_spatial_density_objective_cpp(SEXP parSEXP, SEXP obs_basis_idSEXP, SEXP obs_basis_weightSEXP, SEXP obs_edge_idSEXP, SEXP obs_weightSEXP, SEXP quad_basis_idSEXP, SEXP quad_basis_weightSEXP, SEXP quad_edge_idSEXP, SEXP quad_weightSEXP, SEXP pair_fromSEXP, SEXP pair_toSEXP, SEXP smooth_edge_fromSEXP, SEXP smooth_edge_toSEXP, SEXP smooth_edge_distanceSEXP, SEXP density_floorSEXP, SEXP lambda_etaSEXP, SEXP lambda_s_smoothSEXP, SEXP lambda_s_priorSEXP, SEXP s_prior_meanSEXP, SEXP lambda_edgeSEXP, SEXP n_basisSEXP, SEXP n_edge_coefSEXP, SEXP n_cell_typesSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type obs_basis_id(obs_basis_idSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type obs_basis_weight(obs_basis_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type obs_edge_id(obs_edge_idSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type obs_weight(obs_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type quad_basis_id(quad_basis_idSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type quad_basis_weight(quad_basis_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type quad_edge_id(quad_edge_idSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type quad_weight(quad_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type pair_from(pair_fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type pair_to(pair_toSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smooth_edge_from(smooth_edge_fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type smooth_edge_to(smooth_edge_toSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type smooth_edge_distance(smooth_edge_distanceSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type density_floor(density_floorSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_eta(lambda_etaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_s_smooth(lambda_s_smoothSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_s_prior(lambda_s_priorSEXP);
    Rcpp::traits::input_parameter< const double >::type s_prior_mean(s_prior_meanSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_edge(lambda_edgeSEXP);
    Rcpp::traits::input_parameter< const int >::type n_basis(n_basisSEXP);
    Rcpp::traits::input_parameter< const int >::type n_edge_coef(n_edge_coefSEXP);
    Rcpp::traits::input_parameter< const int >::type n_cell_types(n_cell_typesSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_density_objective_cpp(par, obs_basis_id, obs_basis_weight, obs_edge_id, obs_weight, quad_basis_id, quad_basis_weight, quad_edge_id, quad_weight, pair_from, pair_to, smooth_edge_from, smooth_edge_to, smooth_edge_distance, density_floor, lambda_eta, lambda_s_smooth, lambda_s_prior, s_prior_mean, lambda_edge, n_basis, n_edge_coef, n_cell_types, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// spatial_density_predict_cpp
List spatial_density_predict_cpp(const NumericVector& par, const IntegerMatrix& basis_id, const NumericMatrix& basis_weight, const IntegerMatrix& edge_id, const IntegerVector& pair_from, const IntegerVector& pair_to, const NumericVector& density_floor, const int n_basis, const int n_edge_coef, const int n_cell_types, const int n_threads);
RcppExport SEXP _FastPotts_spatial_density_predict_cpp(SEXP parSEXP, SEXP basis_idSEXP, SEXP basis_weightSEXP, SEXP edge_idSEXP, SEXP pair_fromSEXP, SEXP pair_toSEXP, SEXP density_floorSEXP, SEXP n_basisSEXP, SEXP n_edge_coefSEXP, SEXP n_cell_typesSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type basis_id(basis_idSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type basis_weight(basis_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type edge_id(edge_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type pair_from(pair_fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type pair_to(pair_toSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type density_floor(density_floorSEXP);
    Rcpp::traits::input_parameter< const int >::type n_basis(n_basisSEXP);
    Rcpp::traits::input_parameter< const int >::type n_edge_coef(n_edge_coefSEXP);
    Rcpp::traits::input_parameter< const int >::type n_cell_types(n_cell_typesSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_density_predict_cpp(par, basis_id, basis_weight, edge_id, pair_from, pair_to, density_floor, n_basis, n_edge_coef, n_cell_types, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// simplex_log_density_integral_cpp
List simplex_log_density_integral_cpp(const NumericMatrix& h, const NumericVector& volume, const double taylor_radius, const double close_tol, const double taylor_tol, const int taylor_max_terms, const int gauss_order, const int n_threads);
RcppExport SEXP _FastPotts_simplex_log_density_integral_cpp(SEXP hSEXP, SEXP volumeSEXP, SEXP taylor_radiusSEXP, SEXP close_tolSEXP, SEXP taylor_tolSEXP, SEXP taylor_max_termsSEXP, SEXP gauss_orderSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type volume(volumeSEXP);
    Rcpp::traits::input_parameter< const double >::type taylor_radius(taylor_radiusSEXP);
    Rcpp::traits::input_parameter< const double >::type close_tol(close_tolSEXP);
    Rcpp::traits::input_parameter< const double >::type taylor_tol(taylor_tolSEXP);
    Rcpp::traits::input_parameter< const int >::type taylor_max_terms(taylor_max_termsSEXP);
    Rcpp::traits::input_parameter< const int >::type gauss_order(gauss_orderSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_log_density_integral_cpp(h, volume, taylor_radius, close_tol, taylor_tol, taylor_max_terms, gauss_order, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// spatial_log_density_objective_cpp
List spatial_log_density_objective_cpp(const NumericVector& par, const IntegerMatrix& obs_basis_id, const NumericMatrix& obs_basis_weight, const IntegerMatrix& quad_basis_id, const NumericMatrix& quad_basis_weight, const NumericVector& quad_weight, const IntegerVector& edge_from, const IntegerVector& edge_to, const NumericVector& edge_distance, const double lambda, const int regularization, const double delta, const double sigma, const double lambda_laplacian, const int n_threads);
RcppExport SEXP _FastPotts_spatial_log_density_objective_cpp(SEXP parSEXP, SEXP obs_basis_idSEXP, SEXP obs_basis_weightSEXP, SEXP quad_basis_idSEXP, SEXP quad_basis_weightSEXP, SEXP quad_weightSEXP, SEXP edge_fromSEXP, SEXP edge_toSEXP, SEXP edge_distanceSEXP, SEXP lambdaSEXP, SEXP regularizationSEXP, SEXP deltaSEXP, SEXP sigmaSEXP, SEXP lambda_laplacianSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type obs_basis_id(obs_basis_idSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type obs_basis_weight(obs_basis_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type quad_basis_id(quad_basis_idSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type quad_basis_weight(quad_basis_weightSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type quad_weight(quad_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type edge_from(edge_fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type edge_to(edge_toSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type edge_distance(edge_distanceSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type regularization(regularizationSEXP);
    Rcpp::traits::input_parameter< const double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_laplacian(lambda_laplacianSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_log_density_objective_cpp(par, obs_basis_id, obs_basis_weight, quad_basis_id, quad_basis_weight, quad_weight, edge_from, edge_to, edge_distance, lambda, regularization, delta, sigma, lambda_laplacian, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// spatial_log_density_objective_simplex_cpp
List spatial_log_density_objective_simplex_cpp(const NumericVector& par, const IntegerMatrix& obs_basis_id, const NumericMatrix& obs_basis_weight, const IntegerMatrix& simplex_basis_id, const NumericVector& simplex_volume, const IntegerVector& edge_from, const IntegerVector& edge_to, const NumericVector& edge_distance, const double lambda, const int regularization, const double delta, const double sigma, const double lambda_laplacian, const double taylor_radius, const double close_tol, const double taylor_tol, const int taylor_max_terms, const int gauss_order, const int n_threads);
RcppExport SEXP _FastPotts_spatial_log_density_objective_simplex_cpp(SEXP parSEXP, SEXP obs_basis_idSEXP, SEXP obs_basis_weightSEXP, SEXP simplex_basis_idSEXP, SEXP simplex_volumeSEXP, SEXP edge_fromSEXP, SEXP edge_toSEXP, SEXP edge_distanceSEXP, SEXP lambdaSEXP, SEXP regularizationSEXP, SEXP deltaSEXP, SEXP sigmaSEXP, SEXP lambda_laplacianSEXP, SEXP taylor_radiusSEXP, SEXP close_tolSEXP, SEXP taylor_tolSEXP, SEXP taylor_max_termsSEXP, SEXP gauss_orderSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type obs_basis_id(obs_basis_idSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type obs_basis_weight(obs_basis_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type simplex_basis_id(simplex_basis_idSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type simplex_volume(simplex_volumeSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type edge_from(edge_fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type edge_to(edge_toSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type edge_distance(edge_distanceSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type regularization(regularizationSEXP);
    Rcpp::traits::input_parameter< const double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_laplacian(lambda_laplacianSEXP);
    Rcpp::traits::input_parameter< const double >::type taylor_radius(taylor_radiusSEXP);
    Rcpp::traits::input_parameter< const double >::type close_tol(close_tolSEXP);
    Rcpp::traits::input_parameter< const double >::type taylor_tol(taylor_tolSEXP);
    Rcpp::traits::input_parameter< const int >::type taylor_max_terms(taylor_max_termsSEXP);
    Rcpp::traits::input_parameter< const int >::type gauss_order(gauss_orderSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_log_density_objective_simplex_cpp(par, obs_basis_id, obs_basis_weight, simplex_basis_id, simplex_volume, edge_from, edge_to, edge_distance, lambda, regularization, delta, sigma, lambda_laplacian, taylor_radius, close_tol, taylor_tol, taylor_max_terms, gauss_order, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// spatial_log_density_predict_cpp
List spatial_log_density_predict_cpp(const NumericVector& par, const IntegerMatrix& basis_id, const NumericMatrix& basis_weight, const int n_threads);
RcppExport SEXP _FastPotts_spatial_log_density_predict_cpp(SEXP parSEXP, SEXP basis_idSEXP, SEXP basis_weightSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type basis_id(basis_idSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type basis_weight(basis_weightSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_log_density_predict_cpp(par, basis_id, basis_weight, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// compact_knn_edges_cpp
DataFrame compact_knn_edges_cpp(const IntegerMatrix& nn_idx, const NumericMatrix& nn_dist, const IntegerVector& query_index, const int n_nodes, const double max_distance);
RcppExport SEXP _FastPotts_compact_knn_edges_cpp(SEXP nn_idxSEXP, SEXP nn_distSEXP, SEXP query_indexSEXP, SEXP n_nodesSEXP, SEXP max_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type nn_idx(nn_idxSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type nn_dist(nn_distSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type query_index(query_indexSEXP);
    Rcpp::traits::input_parameter< const int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< const double >::type max_distance(max_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(compact_knn_edges_cpp(nn_idx, nn_dist, query_index, n_nodes, max_distance));
    return rcpp_result_gen;
END_RCPP
}
// compact_undirected_edges_cpp
DataFrame compact_undirected_edges_cpp(const IntegerVector& from, const IntegerVector& to, const NumericVector& distance, const int n_nodes, const double max_distance);
RcppExport SEXP _FastPotts_compact_undirected_edges_cpp(SEXP fromSEXP, SEXP toSEXP, SEXP distanceSEXP, SEXP n_nodesSEXP, SEXP max_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type from(fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type to(toSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< const int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< const double >::type max_distance(max_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(compact_undirected_edges_cpp(from, to, distance, n_nodes, max_distance));
    return rcpp_result_gen;
END_RCPP
}
// estimate_graph_density_cpp
NumericVector estimate_graph_density_cpp(const IntegerVector& from, const IntegerVector& to, const NumericVector& distance, const NumericMatrix& posterior, const double bandwidth, const int mode);
RcppExport SEXP _FastPotts_estimate_graph_density_cpp(SEXP fromSEXP, SEXP toSEXP, SEXP distanceSEXP, SEXP posteriorSEXP, SEXP bandwidthSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type from(fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type to(toSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type posterior(posteriorSEXP);
    Rcpp::traits::input_parameter< const double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< const int >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_graph_density_cpp(from, to, distance, posterior, bandwidth, mode));
    return rcpp_result_gen;
END_RCPP
}
// posterior_js_divergence_edges_cpp
NumericVector posterior_js_divergence_edges_cpp(const NumericMatrix& posterior, const IntegerVector& from, const IntegerVector& to, const double eps);
RcppExport SEXP _FastPotts_posterior_js_divergence_edges_cpp(SEXP posteriorSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type posterior(posteriorSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type from(fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type to(toSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_js_divergence_edges_cpp(posterior, from, to, eps));
    return rcpp_result_gen;
END_RCPP
}
// density_ascent_partition_cpp
List density_ascent_partition_cpp(const IntegerVector& from, const IntegerVector& to, const NumericVector& distance, const NumericVector& density, const NumericVector& posterior_js, const double distance_weight, const double posterior_weight);
RcppExport SEXP _FastPotts_density_ascent_partition_cpp(SEXP fromSEXP, SEXP toSEXP, SEXP distanceSEXP, SEXP densitySEXP, SEXP posterior_jsSEXP, SEXP distance_weightSEXP, SEXP posterior_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type from(fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type to(toSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type density(densitySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type posterior_js(posterior_jsSEXP);
    Rcpp::traits::input_parameter< const double >::type distance_weight(distance_weightSEXP);
    Rcpp::traits::input_parameter< const double >::type posterior_weight(posterior_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(density_ascent_partition_cpp(from, to, distance, density, posterior_js, distance_weight, posterior_weight));
    return rcpp_result_gen;
END_RCPP
}
// density_ascent_active_partition_cpp
List density_ascent_active_partition_cpp(const IntegerVector& from, const IntegerVector& to, const NumericVector& distance, const NumericVector& density, const LogicalVector& active_start, const double distance_weight);
RcppExport SEXP _FastPotts_density_ascent_active_partition_cpp(SEXP fromSEXP, SEXP toSEXP, SEXP distanceSEXP, SEXP densitySEXP, SEXP active_startSEXP, SEXP distance_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type from(fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type to(toSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type density(densitySEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type active_start(active_startSEXP);
    Rcpp::traits::input_parameter< const double >::type distance_weight(distance_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(density_ascent_active_partition_cpp(from, to, distance, density, active_start, distance_weight));
    return rcpp_result_gen;
END_RCPP
}
// build_basin_adjacency_cpp
DataFrame build_basin_adjacency_cpp(const IntegerVector& from, const IntegerVector& to, const NumericVector& distance, const IntegerVector& basin, const NumericVector& density, const NumericMatrix& posterior, const NumericVector& posterior_js, const double eps);
RcppExport SEXP _FastPotts_build_basin_adjacency_cpp(SEXP fromSEXP, SEXP toSEXP, SEXP distanceSEXP, SEXP basinSEXP, SEXP densitySEXP, SEXP posteriorSEXP, SEXP posterior_jsSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type from(fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type to(toSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type basin(basinSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type density(densitySEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type posterior(posteriorSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type posterior_js(posterior_jsSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(build_basin_adjacency_cpp(from, to, distance, basin, density, posterior, posterior_js, eps));
    return rcpp_result_gen;
END_RCPP
}
// tri_barycentric_cpp
List tri_barycentric_cpp(const NumericMatrix& coords, const double s, const NumericVector& origin, const double tol, const int n_threads);
RcppExport SEXP _FastPotts_tri_barycentric_cpp(SEXP coordsSEXP, SEXP sSEXP, SEXP originSEXP, SEXP tolSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type origin(originSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(tri_barycentric_cpp(coords, s, origin, tol, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FastPotts_bcc_barycentric_cpp", (DL_FUNC) &_FastPotts_bcc_barycentric_cpp, 5},
    {"_FastPotts_build_lattice_neighbor_edges_cpp", (DL_FUNC) &_FastPotts_build_lattice_neighbor_edges_cpp, 3},
    {"_FastPotts_build_potts_lbp_graph", (DL_FUNC) &_FastPotts_build_potts_lbp_graph, 3},
    {"_FastPotts_build_potts_lbp_graph_from_edges", (DL_FUNC) &_FastPotts_build_potts_lbp_graph_from_edges, 6},
    {"_FastPotts_hilbert_index_scaled_cpp", (DL_FUNC) &_FastPotts_hilbert_index_scaled_cpp, 3},
    {"_FastPotts_openmp_enabled_cpp", (DL_FUNC) &_FastPotts_openmp_enabled_cpp, 0},
    {"_FastPotts_omp_max_threads_cpp", (DL_FUNC) &_FastPotts_omp_max_threads_cpp, 0},
    {"_FastPotts_potts_lbp_cpp", (DL_FUNC) &_FastPotts_potts_lbp_cpp, 9},
    {"_FastPotts_potts_lbp_parallel_cpp", (DL_FUNC) &_FastPotts_potts_lbp_parallel_cpp, 10},
    {"_FastPotts_spatial_basis_objective_cpp", (DL_FUNC) &_FastPotts_spatial_basis_objective_cpp, 17},
    {"_FastPotts_spatial_basis_predict_cpp", (DL_FUNC) &_FastPotts_spatial_basis_predict_cpp, 8},
    {"_FastPotts_spatial_density_objective_cpp", (DL_FUNC) &_FastPotts_spatial_density_objective_cpp, 24},
    {"_FastPotts_spatial_density_predict_cpp", (DL_FUNC) &_FastPotts_spatial_density_predict_cpp, 11},
    {"_FastPotts_simplex_log_density_integral_cpp", (DL_FUNC) &_FastPotts_simplex_log_density_integral_cpp, 8},
    {"_FastPotts_spatial_log_density_objective_cpp", (DL_FUNC) &_FastPotts_spatial_log_density_objective_cpp, 15},
    {"_FastPotts_spatial_log_density_objective_simplex_cpp", (DL_FUNC) &_FastPotts_spatial_log_density_objective_simplex_cpp, 19},
    {"_FastPotts_spatial_log_density_predict_cpp", (DL_FUNC) &_FastPotts_spatial_log_density_predict_cpp, 4},
    {"_FastPotts_compact_knn_edges_cpp", (DL_FUNC) &_FastPotts_compact_knn_edges_cpp, 5},
    {"_FastPotts_compact_undirected_edges_cpp", (DL_FUNC) &_FastPotts_compact_undirected_edges_cpp, 5},
    {"_FastPotts_estimate_graph_density_cpp", (DL_FUNC) &_FastPotts_estimate_graph_density_cpp, 6},
    {"_FastPotts_posterior_js_divergence_edges_cpp", (DL_FUNC) &_FastPotts_posterior_js_divergence_edges_cpp, 4},
    {"_FastPotts_density_ascent_partition_cpp", (DL_FUNC) &_FastPotts_density_ascent_partition_cpp, 7},
    {"_FastPotts_density_ascent_active_partition_cpp", (DL_FUNC) &_FastPotts_density_ascent_active_partition_cpp, 6},
    {"_FastPotts_build_basin_adjacency_cpp", (DL_FUNC) &_FastPotts_build_basin_adjacency_cpp, 8},
    {"_FastPotts_tri_barycentric_cpp", (DL_FUNC) &_FastPotts_tri_barycentric_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_FastPotts(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
