// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bcc_barycentric_cpp
List bcc_barycentric_cpp(const NumericMatrix& coords, const double s, const NumericVector& origin, const double tol, const int n_threads);
RcppExport SEXP _FastPotts_bcc_barycentric_cpp(SEXP coordsSEXP, SEXP sSEXP, SEXP originSEXP, SEXP tolSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type origin(originSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bcc_barycentric_cpp(coords, s, origin, tol, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// build_potts_lbp_graph
List build_potts_lbp_graph(SEXP mat, const bool drop_diagonal, const bool check_reverse);
RcppExport SEXP _FastPotts_build_potts_lbp_graph(SEXP matSEXP, SEXP drop_diagonalSEXP, SEXP check_reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const bool >::type drop_diagonal(drop_diagonalSEXP);
    Rcpp::traits::input_parameter< const bool >::type check_reverse(check_reverseSEXP);
    rcpp_result_gen = Rcpp::wrap(build_potts_lbp_graph(mat, drop_diagonal, check_reverse));
    return rcpp_result_gen;
END_RCPP
}
// build_potts_lbp_graph_from_edges
List build_potts_lbp_graph_from_edges(const IntegerVector& from, const IntegerVector& to, const NumericVector& weights, const int n_nodes, const bool symmetric, const bool check_reverse);
RcppExport SEXP _FastPotts_build_potts_lbp_graph_from_edges(SEXP fromSEXP, SEXP toSEXP, SEXP weightsSEXP, SEXP n_nodesSEXP, SEXP symmetricSEXP, SEXP check_reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type from(fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type to(toSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< const bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< const bool >::type check_reverse(check_reverseSEXP);
    rcpp_result_gen = Rcpp::wrap(build_potts_lbp_graph_from_edges(from, to, weights, n_nodes, symmetric, check_reverse));
    return rcpp_result_gen;
END_RCPP
}
// hilbert_index_scaled_cpp
SEXP hilbert_index_scaled_cpp(NumericMatrix coords, int bits, bool return_scaled);
RcppExport SEXP _FastPotts_hilbert_index_scaled_cpp(SEXP coordsSEXP, SEXP bitsSEXP, SEXP return_scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< int >::type bits(bitsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_scaled(return_scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(hilbert_index_scaled_cpp(coords, bits, return_scaled));
    return rcpp_result_gen;
END_RCPP
}
// openmp_enabled_cpp
bool openmp_enabled_cpp();
RcppExport SEXP _FastPotts_openmp_enabled_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(openmp_enabled_cpp());
    return rcpp_result_gen;
END_RCPP
}
// omp_max_threads_cpp
int omp_max_threads_cpp();
RcppExport SEXP _FastPotts_omp_max_threads_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(omp_max_threads_cpp());
    return rcpp_result_gen;
END_RCPP
}
// potts_lbp_cpp
List potts_lbp_cpp(const IntegerVector& adj_ptr, const IntegerVector& adj_idx, const IntegerVector& rev_idx, const NumericVector& edge_weights, const NumericMatrix& node_potential, const int max_iter, const float damping, const float tol, const bool synchronous);
RcppExport SEXP _FastPotts_potts_lbp_cpp(SEXP adj_ptrSEXP, SEXP adj_idxSEXP, SEXP rev_idxSEXP, SEXP edge_weightsSEXP, SEXP node_potentialSEXP, SEXP max_iterSEXP, SEXP dampingSEXP, SEXP tolSEXP, SEXP synchronousSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type adj_ptr(adj_ptrSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type adj_idx(adj_idxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type rev_idx(rev_idxSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type edge_weights(edge_weightsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type node_potential(node_potentialSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const float >::type damping(dampingSEXP);
    Rcpp::traits::input_parameter< const float >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const bool >::type synchronous(synchronousSEXP);
    rcpp_result_gen = Rcpp::wrap(potts_lbp_cpp(adj_ptr, adj_idx, rev_idx, edge_weights, node_potential, max_iter, damping, tol, synchronous));
    return rcpp_result_gen;
END_RCPP
}
// potts_lbp_parallel_cpp
List potts_lbp_parallel_cpp(const IntegerVector& adj_ptr, const IntegerVector& adj_idx, const IntegerVector& rev_idx, const NumericVector& edge_weights, const NumericMatrix& node_potential, const int max_iter, const float damping, const float tol, Nullable<int> n_threads, const bool verbose);
RcppExport SEXP _FastPotts_potts_lbp_parallel_cpp(SEXP adj_ptrSEXP, SEXP adj_idxSEXP, SEXP rev_idxSEXP, SEXP edge_weightsSEXP, SEXP node_potentialSEXP, SEXP max_iterSEXP, SEXP dampingSEXP, SEXP tolSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type adj_ptr(adj_ptrSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type adj_idx(adj_idxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type rev_idx(rev_idxSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type edge_weights(edge_weightsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type node_potential(node_potentialSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const float >::type damping(dampingSEXP);
    Rcpp::traits::input_parameter< const float >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(potts_lbp_parallel_cpp(adj_ptr, adj_idx, rev_idx, edge_weights, node_potential, max_iter, damping, tol, n_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// spatial_basis_objective_cpp
List spatial_basis_objective_cpp(const NumericVector& par, const IntegerMatrix& basis_id, const NumericMatrix& basis_weight, const IntegerVector& gene_index, const NumericMatrix& log_signature, const IntegerVector& edge_from, const IntegerVector& edge_to, const double lambda, const int regularization, const double delta, const double sigma, const int n_threads, const int n_basis, const int n_cell_types);
RcppExport SEXP _FastPotts_spatial_basis_objective_cpp(SEXP parSEXP, SEXP basis_idSEXP, SEXP basis_weightSEXP, SEXP gene_indexSEXP, SEXP log_signatureSEXP, SEXP edge_fromSEXP, SEXP edge_toSEXP, SEXP lambdaSEXP, SEXP regularizationSEXP, SEXP deltaSEXP, SEXP sigmaSEXP, SEXP n_threadsSEXP, SEXP n_basisSEXP, SEXP n_cell_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type basis_id(basis_idSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type basis_weight(basis_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type gene_index(gene_indexSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type log_signature(log_signatureSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type edge_from(edge_fromSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type edge_to(edge_toSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type regularization(regularizationSEXP);
    Rcpp::traits::input_parameter< const double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_basis(n_basisSEXP);
    Rcpp::traits::input_parameter< const int >::type n_cell_types(n_cell_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_basis_objective_cpp(par, basis_id, basis_weight, gene_index, log_signature, edge_from, edge_to, lambda, regularization, delta, sigma, n_threads, n_basis, n_cell_types));
    return rcpp_result_gen;
END_RCPP
}
// spatial_basis_predict_cpp
List spatial_basis_predict_cpp(const NumericVector& par, const IntegerMatrix& basis_id, const NumericMatrix& basis_weight, const IntegerVector& gene_index, const NumericMatrix& log_signature, const int n_basis, const int n_threads, const int n_cell_types);
RcppExport SEXP _FastPotts_spatial_basis_predict_cpp(SEXP parSEXP, SEXP basis_idSEXP, SEXP basis_weightSEXP, SEXP gene_indexSEXP, SEXP log_signatureSEXP, SEXP n_basisSEXP, SEXP n_threadsSEXP, SEXP n_cell_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type basis_id(basis_idSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type basis_weight(basis_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type gene_index(gene_indexSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type log_signature(log_signatureSEXP);
    Rcpp::traits::input_parameter< const int >::type n_basis(n_basisSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_cell_types(n_cell_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_basis_predict_cpp(par, basis_id, basis_weight, gene_index, log_signature, n_basis, n_threads, n_cell_types));
    return rcpp_result_gen;
END_RCPP
}
// tri_barycentric_cpp
List tri_barycentric_cpp(const NumericMatrix& coords, const double s, const NumericVector& origin, const double tol, const int n_threads);
RcppExport SEXP _FastPotts_tri_barycentric_cpp(SEXP coordsSEXP, SEXP sSEXP, SEXP originSEXP, SEXP tolSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type origin(originSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(tri_barycentric_cpp(coords, s, origin, tol, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FastPotts_bcc_barycentric_cpp", (DL_FUNC) &_FastPotts_bcc_barycentric_cpp, 5},
    {"_FastPotts_build_potts_lbp_graph", (DL_FUNC) &_FastPotts_build_potts_lbp_graph, 3},
    {"_FastPotts_build_potts_lbp_graph_from_edges", (DL_FUNC) &_FastPotts_build_potts_lbp_graph_from_edges, 6},
    {"_FastPotts_hilbert_index_scaled_cpp", (DL_FUNC) &_FastPotts_hilbert_index_scaled_cpp, 3},
    {"_FastPotts_openmp_enabled_cpp", (DL_FUNC) &_FastPotts_openmp_enabled_cpp, 0},
    {"_FastPotts_omp_max_threads_cpp", (DL_FUNC) &_FastPotts_omp_max_threads_cpp, 0},
    {"_FastPotts_potts_lbp_cpp", (DL_FUNC) &_FastPotts_potts_lbp_cpp, 9},
    {"_FastPotts_potts_lbp_parallel_cpp", (DL_FUNC) &_FastPotts_potts_lbp_parallel_cpp, 10},
    {"_FastPotts_spatial_basis_objective_cpp", (DL_FUNC) &_FastPotts_spatial_basis_objective_cpp, 14},
    {"_FastPotts_spatial_basis_predict_cpp", (DL_FUNC) &_FastPotts_spatial_basis_predict_cpp, 8},
    {"_FastPotts_tri_barycentric_cpp", (DL_FUNC) &_FastPotts_tri_barycentric_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_FastPotts(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
