# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcc_barycentric_cpp <- function(coords, s, origin, tol = 1e-10, n_threads = 0L) {
    .Call(`_FastPotts_bcc_barycentric_cpp`, coords, s, origin, tol, n_threads)
}

#' Build lattice-neighbor edges from integer basis coordinates
#'
#' Internal helper for triangular and BCC spatial basis graphs. This avoids
#' the large string-key and neighbor-matrix temporaries used by the R fallback.
#'
#' @param basis_lattice Integer matrix of basis lattice coordinates.
#' @param basis_id Integer; 0 for triangular 2D, 1 for BCC 3D.
#' @param s Positive mesh size.
#'
#' @return A data frame with one row per undirected edge and columns `from`,
#'   `to`, and `distance`. Node indices are 1-based.
#' @keywords internal
#' @noRd
build_lattice_neighbor_edges_cpp <- function(basis_lattice, basis_id, s) {
    .Call(`_FastPotts_build_lattice_neighbor_edges_cpp`, basis_lattice, basis_id, s)
}

#' Build Potts-LBP graph inputs from a sparse adjacency matrix
#'
#' Converts a square sparse adjacency matrix of class `dgCMatrix` into the
#' CSR-like graph representation expected by `potts_lbp()`.
#'
#' The input matrix is interpreted as a directed adjacency matrix stored in
#' CSC format. If the graph is undirected, each edge should appear twice:
#' once at `(i, j)` and once at `(j, i)`. The function constructs:
#'
#' - `adj_ptr`: CSR row pointer array
#' - `adj_idx`: destination node index for each directed edge
#' - `rev_idx`: index of the reverse directed edge
#' - `edge_weights`: edge weights in the same order as `adj_idx`
#'
#' Node indices in the returned object are **0-based**, matching the C++
#' indexing expected by `potts_lbp()`.
#'
#' @param mat A square sparse matrix of class `dgCMatrix`. Off-diagonal nonzero
#'   entries define directed edges; diagonal entries are ignored by default.
#' @param drop_diagonal Logical; if `TRUE` (default), diagonal entries are
#'   ignored. If `FALSE`, diagonal entries are retained, but then each diagonal
#'   entry is its own reverse.
#' @param check_reverse Logical; if `TRUE` (default), each directed edge must
#'   have a matching reverse edge or an error is thrown.
#'
#' @return A list with components:
#' \describe{
#'   \item{adj_ptr}{Integer vector of length `N + 1` giving CSR row pointers.}
#'   \item{adj_idx}{Integer vector of length `E` of 0-based destination nodes.}
#'   \item{rev_idx}{Integer vector of length `E`; `rev_idx[e]` is the index of
#'     the reverse directed edge for edge `e`.}
#'   \item{edge_weights}{Numeric vector of length `E` of edge weights in the
#'     same order as `adj_idx`.}
#'   \item{n_nodes}{Number of nodes.}
#'   \item{n_edges}{Number of directed edges after optional diagonal removal.}
#' }
#'
#' @details
#' A `dgCMatrix` is stored in compressed sparse column (CSC) format. This helper
#' first counts outgoing edges per row in order to build a CSR representation,
#' then fills the directed edge list, and finally computes reverse-edge indices.
#'
#' Reverse edges are found efficiently by binary-searching for entry `(j, i)`
#' in column `i` for each entry `(i, j)`. For sparse k-NN graphs, this is
#' typically very fast because each column contains only a small number of
#' nonzeros.
#'
#' The returned edge order is by source row, then by the original CSC scan order.
#' This is suitable for the LBP implementation, which only requires consistency
#' among `adj_ptr`, `adj_idx`, `rev_idx`, and `edge_weights`.
#'
#' @examples
#' \dontrun{
#' library(Matrix)
#'
#' W <- sparseMatrix(
#'   i = c(1,2,1,3,2,3),
#'   j = c(2,1,3,1,3,2),
#'   x = c(0.7,0.7,0.4,0.4,0.9,0.9),
#'   dims = c(3,3)
#' )
#'
#' g <- build_potts_lbp_graph(W)
#'
#' str(g)
#' # g$adj_ptr
#' # g$adj_idx
#' # g$rev_idx
#' # g$edge_weights
#' }
#'
#' @export
build_potts_lbp_graph <- function(mat, drop_diagonal = TRUE, check_reverse = TRUE) {
    .Call(`_FastPotts_build_potts_lbp_graph`, mat, drop_diagonal, check_reverse)
}

#' Build Potts-LBP graph inputs directly from an edge list
#'
#' Builds the CSR-like graph representation expected by `potts_lbp()` from a
#' directed edge list without first materializing a sparse matrix.
#'
#' Duplicate directed edges are deduplicated so that each directed edge appears
#' at most once in the returned graph. If duplicate `(from, to)` entries are
#' supplied with different weights, an error is thrown.
#'
#' Node indices supplied in `from` and `to` are **1-based R indices**. Returned
#' graph indices remain **0-based**, matching the C++ indexing expected by
#' `potts_lbp()`.
#'
#' @param from Integer vector of 1-based source node indices.
#' @param to Integer vector of 1-based destination node indices.
#' @param weights Numeric vector of edge weights. Must either have length 1,
#'   in which case the same weight is used for every input edge, or the same
#'   length as `from`.
#' @param n_nodes Integer number of nodes in the graph.
#' @param symmetric Logical; if `TRUE`, each input edge `(u, v)` is treated as
#'   undirected and inserted in both directions `(u, v)` and `(v, u)`.
#' @param check_reverse Logical; if `TRUE` (default), each directed edge must
#'   have a matching reverse edge after duplicate aggregation.
#'
#' @return A list with the same structure as [build_potts_lbp_graph()].
#'
#' @keywords internal
build_potts_lbp_graph_from_edges <- function(from, to, weights, n_nodes, symmetric = FALSE, check_reverse = TRUE) {
    .Call(`_FastPotts_build_potts_lbp_graph_from_edges`, from, to, weights, n_nodes, symmetric, check_reverse)
}

hilbert_index_scaled_cpp <- function(coords, bits, return_scaled = FALSE) {
    .Call(`_FastPotts_hilbert_index_scaled_cpp`, coords, bits, return_scaled)
}

openmp_enabled_cpp <- function() {
    .Call(`_FastPotts_openmp_enabled_cpp`)
}

omp_max_threads_cpp <- function() {
    .Call(`_FastPotts_omp_max_threads_cpp`)
}

#' Loopy belief propagation for a Potts model on a sparse directed graph
#'
#' Runs sum-product loopy belief propagation (LBP) for a Potts model with
#' node-specific unary log-potentials and edge-specific pairwise Potts weights.
#'
#' The graph is supplied in CSR-like directed adjacency form. Each undirected
#' edge should appear twice in `adj_idx`: once as `u -> v` and once as
#' `v -> u`. The vector `rev_idx` maps each directed edge to the index of its
#' reverse directed edge.
#'
#' The pairwise potential is parameterized as
#' \deqn{
#' \psi_{uv}(a,b) = \exp(w_{uv}) \text{ if } a=b,\quad 1 \text{ otherwise},
#' }
#' where `edge_weights[edge] = w_{uv}` is the log same-label preference for the
#' directed edge `u -> v`. In most applications the two directions of an
#' undirected edge will have the same weight.
#'
#' The unary potential is parameterized by `node_potential`, whose `(i, k)` entry
#' is the log unary potential for node `i` and label `k`.
#'
#' Message updates are performed in log-space for numerical stability. The
#' returned node marginals are normalized probabilities on the original scale.
#'
#' @param adj_ptr Integer vector of length `N + 1` giving CSR row pointers for
#'   the directed adjacency structure. Directed neighbors of node `u` are stored
#'   in `adj_idx[adj_ptr[u] : adj_ptr[u + 1] - 1]` using 0-based C++ indexing.
#' @param adj_idx Integer vector of length `E` containing the destination node
#'   for each directed edge. Values are expected to be 0-based node indices.
#' @param rev_idx Integer vector of length `E` such that `rev_idx[e]` is the
#'   directed-edge index of the reverse of edge `e`.
#' @param edge_weights Numeric vector of length `E` containing log same-label
#'   Potts weights for each directed edge.
#' @param node_potential Numeric matrix of dimension `N x K` containing log
#'   unary potentials.
#' @param max_iter Maximum number of LBP sweeps.
#' @param damping Damping parameter in `(0, 1]`. Values below 1 blend each new
#'   message with the previous message to improve stability on loopy graphs.
#'   Default is `1.0`, corresponding to no damping.
#' @param tol Convergence tolerance. Iteration stops early when the maximum
#'   absolute message change in a sweep is below `tol`. Default is `1e-2`.
#' @param synchronous Logical; if `TRUE` (default), uses synchronous updates
#'   with a second message buffer. If `FALSE`, uses in-place asynchronous
#'   updates.
#'
#' @return A list with components:
#' \describe{
#'   \item{marginals}{`N x K` numeric matrix of approximate node marginals.}
#'   \item{iterations}{Number of sweeps performed.}
#'   \item{max_delta}{Maximum absolute message change in the final sweep.}
#' }
#'
#' @details
#' Let
#' \deqn{
#' H_i(k) = \log \phi_i(k) + \sum_{\ell \in N(i)} \log m_{\ell \to i}(k).
#' }
#' For the directed edge `u -> v`, the cavity field is
#' \deqn{
#' h_{u \to v}(k) = H_u(k) - \log m_{v \to u}(k).
#' }
#' With the Potts parameterization above, the message update simplifies to
#' \deqn{
#' m_{u \to v}(k) \propto S_{u \to v} +
#'   (\exp(w_{uv}) - 1)\exp(h_{u \to v}(k)),
#' }
#' where
#' \deqn{
#' S_{u \to v} = \sum_a \exp(h_{u \to v}(a)).
#' }
#' This reduces each per-edge update from `O(K^2)` for a general pairwise model
#' to `O(K)` for the Potts model.
#'
#' @examples
#' \dontrun{
#' # Suppose graph contains directed edges for both directions of each
#' # undirected edge, stored in CSR form.
#' fit <- potts_lbp_cpp(
#'   adj_ptr = adj_ptr,
#'   adj_idx = adj_idx,
#'   rev_idx = rev_idx,
#'   edge_weights = edge_weights,
#'   node_potential = node_potential
#' )
#'
#' fit$marginals
#' fit$iterations
#' fit$max_delta
#'
#' # Example with non-default controls
#' fit2 <- potts_lbp_cpp(
#'   adj_ptr = adj_ptr,
#'   adj_idx = adj_idx,
#'   rev_idx = rev_idx,
#'   edge_weights = edge_weights,
#'   node_potential = node_potential,
#'   max_iter = 100,
#'   damping = 0.5,
#'   tol = 1e-4,
#'   synchronous = FALSE
#' )
#' }
#'
#' @export
potts_lbp_cpp <- function(adj_ptr, adj_idx, rev_idx, edge_weights, node_potential, max_iter = 50L, damping = 1.0, tol = 1e-2, synchronous = TRUE) {
    .Call(`_FastPotts_potts_lbp_cpp`, adj_ptr, adj_idx, rev_idx, edge_weights, node_potential, max_iter, damping, tol, synchronous)
}

#' Parallel synchronous loopy belief propagation for a Potts model
#'
#' Synchronous sum-product loopy belief propagation (LBP) for a Potts model on
#' a sparse directed graph stored in CSR-like form.
#'
#' This version uses OpenMP to parallelize the message-update sweep over source
#' nodes. The rebuild of the cached incoming fields is performed serially.
#'
#' @param adj_ptr Integer vector of length `N + 1` giving CSR row pointers.
#' @param adj_idx Integer vector of length `E` containing 0-based destination
#'   node indices for each directed edge.
#' @param rev_idx Integer vector of length `E` such that `rev_idx[e]` is the
#'   directed-edge index of the reverse of edge `e`.
#' @param edge_weights Numeric vector of length `E` containing log same-label
#'   Potts weights for each directed edge.
#' @param node_potential Numeric matrix of dimension `N x K` containing log
#'   unary potentials.
#' @param max_iter Maximum number of LBP sweeps.
#' @param damping Damping parameter in `(0, 1]`. Default is `1.0`.
#' @param tol Convergence tolerance on the maximum absolute message change per
#'   sweep. Default is `1e-2`.
#' @param n_threads Number of OpenMP threads to use. If `NULL`, uses the
#'   current OpenMP default.
#' @param verbose If `TRUE`, prints the maximum and mean message change at each iteration.
#'
#' @return A list with components:
#' \describe{
#'   \item{marginals}{`N x K` numeric matrix of approximate node marginals.}
#'   \item{iterations}{Number of sweeps performed.}
#'   \item{max_delta}{Maximum absolute message change in the final sweep.}
#' }
#'
#' @details
#' Let
#' \deqn{
#' H_i(k) = \log \phi_i(k) + \sum_{\ell \in N(i)} \log m_{\ell \to i}(k).
#' }
#' For the directed edge `u -> v`, the cavity field is
#' \deqn{
#' h_{u \to v}(k) = H_u(k) - \log m_{v \to u}(k).
#' }
#' With the Potts parameterization above, the message update simplifies to
#' \deqn{
#' m_{u \to v}(k) \propto S_{u \to v} +
#'   (\exp(w_{uv}) - 1)\exp(h_{u \to v}(k)),
#' }
#' where
#' \deqn{
#' S_{u \to v} = \sum_a \exp(h_{u \to v}(a)).
#' }
#' This reduces each per-edge update from `O(K^2)` for a general pairwise model
#' to `O(K)` for the Potts model.
#'
#' @export
potts_lbp_parallel_cpp <- function(adj_ptr, adj_idx, rev_idx, edge_weights, node_potential, max_iter = 50L, damping = 1.0, tol = 1e-2, n_threads = NULL, verbose = FALSE) {
    .Call(`_FastPotts_potts_lbp_parallel_cpp`, adj_ptr, adj_idx, rev_idx, edge_weights, node_potential, max_iter, damping, tol, n_threads, verbose)
}

spatial_basis_objective_cpp <- function(par, basis_id, basis_weight, gene_index, log_signature, edge_from, edge_to, edge_distance, lambda, regularization, delta, sigma, purity, purity_lambda, n_threads, n_basis, n_cell_types) {
    .Call(`_FastPotts_spatial_basis_objective_cpp`, par, basis_id, basis_weight, gene_index, log_signature, edge_from, edge_to, edge_distance, lambda, regularization, delta, sigma, purity, purity_lambda, n_threads, n_basis, n_cell_types)
}

spatial_basis_predict_cpp <- function(par, basis_id, basis_weight, gene_index, log_signature, n_basis, n_threads, n_cell_types) {
    .Call(`_FastPotts_spatial_basis_predict_cpp`, par, basis_id, basis_weight, gene_index, log_signature, n_basis, n_threads, n_cell_types)
}

#' @noRd
spatial_density_objective_cpp <- function(par, obs_basis_id, obs_basis_weight, obs_edge_id, obs_weight, quad_basis_id, quad_basis_weight, quad_edge_id, quad_weight, pair_from, pair_to, smooth_edge_from, smooth_edge_to, smooth_edge_distance, density_floor, lambda_eta, lambda_s_smooth, lambda_s_prior, s_prior_mean, lambda_edge, n_basis, n_edge_coef, n_cell_types, n_threads) {
    .Call(`_FastPotts_spatial_density_objective_cpp`, par, obs_basis_id, obs_basis_weight, obs_edge_id, obs_weight, quad_basis_id, quad_basis_weight, quad_edge_id, quad_weight, pair_from, pair_to, smooth_edge_from, smooth_edge_to, smooth_edge_distance, density_floor, lambda_eta, lambda_s_smooth, lambda_s_prior, s_prior_mean, lambda_edge, n_basis, n_edge_coef, n_cell_types, n_threads)
}

#' @noRd
spatial_density_predict_cpp <- function(par, basis_id, basis_weight, edge_id, pair_from, pair_to, density_floor, n_basis, n_edge_coef, n_cell_types, n_threads) {
    .Call(`_FastPotts_spatial_density_predict_cpp`, par, basis_id, basis_weight, edge_id, pair_from, pair_to, density_floor, n_basis, n_edge_coef, n_cell_types, n_threads)
}

#' Integrate a log-linear density over simplexes
#'
#' For each row of `h`, computes `volume * E[exp(sum_i lambda_i h_i)]`
#' where `lambda` is uniform over the triangle or tetrahedron. The gradient
#' columns are the derivatives with respect to the corresponding vertex values.
#'
#' @keywords internal
#' @noRd
simplex_log_density_integral_cpp <- function(h, volume, taylor_radius, close_tol, taylor_tol, taylor_max_terms, gauss_order, n_threads) {
    .Call(`_FastPotts_simplex_log_density_integral_cpp`, h, volume, taylor_radius, close_tol, taylor_tol, taylor_max_terms, gauss_order, n_threads)
}

#' @noRd
spatial_log_density_objective_cpp <- function(par, obs_basis_id, obs_basis_weight, quad_basis_id, quad_basis_weight, quad_weight, edge_from, edge_to, edge_distance, lambda, regularization, delta, sigma, lambda_laplacian, n_threads) {
    .Call(`_FastPotts_spatial_log_density_objective_cpp`, par, obs_basis_id, obs_basis_weight, quad_basis_id, quad_basis_weight, quad_weight, edge_from, edge_to, edge_distance, lambda, regularization, delta, sigma, lambda_laplacian, n_threads)
}

#' @noRd
spatial_log_density_predict_cpp <- function(par, basis_id, basis_weight, n_threads) {
    .Call(`_FastPotts_spatial_log_density_predict_cpp`, par, basis_id, basis_weight, n_threads)
}

#' Compact directed KNN results into undirected graph edges
#'
#' Internal C++ helper for `partition_transcripts_watershed()`.
#'
#' @keywords internal
#' @noRd
compact_knn_edges_cpp <- function(nn_idx, nn_dist, query_index, n_nodes, max_distance) {
    .Call(`_FastPotts_compact_knn_edges_cpp`, nn_idx, nn_dist, query_index, n_nodes, max_distance)
}

#' Compact an edge list into unique undirected graph edges
#'
#' Internal C++ helper for `partition_transcripts_watershed()`.
#'
#' @keywords internal
#' @noRd
compact_undirected_edges_cpp <- function(from, to, distance, n_nodes, max_distance) {
    .Call(`_FastPotts_compact_undirected_edges_cpp`, from, to, distance, n_nodes, max_distance)
}

#' Estimate graph transcript density
#'
#' Internal C++ helper for `partition_transcripts_watershed()`.
#'
#' @keywords internal
estimate_graph_density_cpp <- function(from, to, distance, posterior, bandwidth, mode) {
    .Call(`_FastPotts_estimate_graph_density_cpp`, from, to, distance, posterior, bandwidth, mode)
}

#' Compute edge-level posterior Jensen-Shannon divergence
#'
#' Internal C++ helper for `partition_transcripts_watershed()`.
#'
#' @keywords internal
posterior_js_divergence_edges_cpp <- function(posterior, from, to, eps = 1e-12) {
    .Call(`_FastPotts_posterior_js_divergence_edges_cpp`, posterior, from, to, eps)
}

#' Assign graph nodes to density modes by ascent
#'
#' Internal C++ helper for `partition_transcripts_watershed()`.
#'
#' @keywords internal
density_ascent_partition_cpp <- function(from, to, distance, density, posterior_js, distance_weight, posterior_weight) {
    .Call(`_FastPotts_density_ascent_partition_cpp`, from, to, distance, density, posterior_js, distance_weight, posterior_weight)
}

#' Assign active graph nodes to density modes by ascent
#'
#' Internal C++ helper for basis-level watershed partitioning. Parents are
#' computed over all graph nodes, but basin labels are assigned only for
#' active starts. Inactive nodes can therefore be used as pass-through nodes
#' along ascent paths without producing their own output basins.
#'
#' @keywords internal
#' @noRd
density_ascent_active_partition_cpp <- function(from, to, distance, density, active_start, distance_weight) {
    .Call(`_FastPotts_density_ascent_active_partition_cpp`, from, to, distance, density, active_start, distance_weight)
}

#' Build basin adjacency and saddle diagnostics
#'
#' Internal C++ helper for `partition_transcripts_watershed()`.
#'
#' @keywords internal
build_basin_adjacency_cpp <- function(from, to, distance, basin, density, posterior, posterior_js, eps = 1e-12) {
    .Call(`_FastPotts_build_basin_adjacency_cpp`, from, to, distance, basin, density, posterior, posterior_js, eps)
}

tri_barycentric_cpp <- function(coords, s, origin, tol = 1e-10, n_threads = 0L) {
    .Call(`_FastPotts_tri_barycentric_cpp`, coords, s, origin, tol, n_threads)
}

