#' Barycentric coordinates on a triangular lattice
#'
#' Computes the three active piecewise-linear basis functions for each point on
#' a triangular lattice. The lattice is generated by basis vectors
#' `(s, 0)` and `(s / 2, sqrt(3) * s / 2)`, optionally shifted by `origin`.
#'
#' For each query point, the function finds the containing equilateral triangle
#' and returns its three vertices and barycentric weights. Away from triangle
#' boundaries exactly three basis functions are non-zero. On edges or vertices,
#' some returned weights may be zero. The support of each lattice-point basis
#' function is a regular hexagon.
#'
#' The Delaunay triangles are equilateral with side length `s`. Thus for
#' `s = 1`, each triangle has side length `1`. The regular hexagonal support of
#' each lattice-point basis function has side length `s`, vertex-to-vertex
#' diameter `2 * s`, and flat-to-flat diameter `sqrt(3) * s`.
#'
#' @param coords Numeric matrix or data frame with two columns containing query
#'   coordinates.
#' @param s Positive numeric mesh size. This is the side length of each
#'   equilateral triangle.
#' @param origin Numeric vector of length two giving the lattice origin.
#' @param tol Numeric tolerance used for triangle boundary checks.
#'
#' @return A list with components:
#' \describe{
#'   \item{weights}{Numeric matrix with three barycentric weights per row of
#'     `coords`.}
#'   \item{points}{Numeric array of dimension `n x 3 x 2` containing the three
#'     active lattice points for each query point.}
#'   \item{lattice}{Integer array of dimension `n x 3 x 2` containing the
#'     triangular-lattice coordinates before multiplying by `s` and adding
#'     `origin`.}
#' }
#'
#' @examples
#' coords <- matrix(c(0.25, 0.25), ncol = 2)
#' tri <- tri_barycentric(coords, s = 1)
#' rowSums(tri$weights)
#'
#' @export
tri_barycentric <- function(coords, s, origin = c(0, 0), tol = 1e-10) {
    coords <- as.matrix(coords)

    if (ncol(coords) != 2L) {
        stop("coords must have exactly 2 columns.")
    }

    if (
        length(s) != 1L ||
        !is.finite(s) ||
        s <= 0
    ) {
        stop("s must be a positive finite number.")
    }

    if (length(origin) != 2L || any(!is.finite(origin))) {
        stop("origin must be a finite numeric vector of length 2.")
    }

    if (
        length(tol) != 1L ||
        !is.finite(tol) ||
        tol < 0
    ) {
        stop("tol must be a non-negative finite number.")
    }

    tri_barycentric_cpp(coords, s = as.numeric(s), origin = as.numeric(origin), tol = as.numeric(tol))
}
